### ISSUE TITLE
Test GPT AI

### ISSUE THREAD

**Issue by MenlyCSE** [STEM-E-Youth-Career-Development-Program/app-7#15]
Test to see if you can use ChatGPT's API for our webpage. I think they give you $5 credits after signing up, but if it's not free, comment to inform us

https://platform.openai.com/docs/overview

**Comment by J12aGuan** [comment]
This shows the free tier rate limits for ChatGPT: https://platform.openai.com/docs/guides/rate-limits/usage-tiers?context=tier-free
