### ISSUE TITLE
Getting started on the front-end

### ISSUE THREAD

**Issue by MenlyCSE** [STEM-E-Youth-Career-Development-Program/app-7#19]
### Things to consider adding
- Import file feature (e.g., [image import](https://github.com/MenlyCSE/tesseract-OCR-template)).
- Text input box for user notes in text 
- Submit button for the file or text; after clicking the button, the data gets processed, stored, or whatever
- Start coding the overall looks of the website, including titles, background, color, font-size...
- Navigation bar in case we have more than one page

### Figma design references
Link 1: https://www.figma.com/design/Pj5Et89SAZDB8QdG9KVJ7f/Note-Sage?node-id=0-1&t=xtGZ4nBthe8uipbp-0
Link 2: https://www.figma.com/design/KvCRYID2rrJUPZ37rMhTnR/STEM-E-Note-Summarizer?node-id=0-1&t=VhwcU3JsrA488KEZ-0

**Comment by SachchitBalamurugan** [comment]
![Image](https://github.com/user-attachments/assets/8df6a86e-dbe1-41a7-87fb-07b7dcb6c331)

Made the front end and implemented the Gemini API to generate a result when a user inputs a prompt and clicks summarize, everything else for now is a place holder

**Comment by MenlyCSE** [comment]
Added the input tabs and CSS color palette 
![Image](https://github.com/user-attachments/assets/f9e1a45a-bb39-45fd-905d-4fe30c568397)
