### ISSUE TITLE
AI summarize Research

### ISSUE THREAD

**Issue by MenlyCSE** [STEM-E-Youth-Career-Development-Program/app-7#2]
Research on how to use AI to summarize text for websites

**Comment by R1tMah** [comment]
We could use Open AI's API to try and summarize it. All we would have to do is plug in the text from reading in the pdf into a prompt for the AI and use the information. Open AI isn't the only option as there are also things like Hugging Face or Google Cloud that we can also utilize to summarize the text we receive. 

If we wanted to create our own model that would be a very long process and one that I'm not sure follows our "keep it simple" policy. If you want me to go in-depth, I can but I think the time it would take to learn more about it as well as implementing this in a web application is very long.

**Comment by J12aGuan** [comment]
This is the link to the document: https://docs.google.com/document/d/1H_FfUC634Yl2Z9lNI3dop6pEcyRLIgucXkXDp4hOyFs/edit?usp=sharing

**Comment by MenlyCSE** [comment]
**Reference price model:** [Google's API](https://ai.google.dev/pricing)

**Comment by randompotato0112** [comment]
**Link to my research** -> https://docs.google.com/document/d/1kapPS_Mj5KZ0rBbuFw5YHtluOP_NodPIRBL2uPhBfgQ/edit

Btw: I won't be able to attend most of the meeting because of a hurricane coming my way so I will most likely leave around 1:20pm CST
