### ISSUE TITLE
AI generate Quiz

### ISSUE THREAD

**Issue by MenlyCSE** [STEM-E-Youth-Career-Development-Program/app-7#3]
Research on how to use AI to generate a quiz depending on what a user submits
**Reference:** https://devpost.com/software/quiznote

**Comment by J12aGuan** [comment]
This is the link to the document: https://docs.google.com/document/d/1H_FfUC634Yl2Z9lNI3dop6pEcyRLIgucXkXDp4hOyFs/edit?usp=sharing
