### ISSUE TITLE
Website Design Brainstorm

### ISSUE THREAD

**Issue by MenlyCSE** [STEM-E-Youth-Career-Development-Program/app-7#4]
Use Figma or any other application to brainstorm the website's design for this idea: https://docs.google.com/document/d/17If3Xeao7IWeceAFBaAvmSf0Jsoqgj8q1zytesnEsDQ/edit

**Comment by MenlyCSE** [comment]
Here is my Figma design: 
https://www.figma.com/design/Pj5Et89SAZDB8QdG9KVJ7f/Note-Sage?node-id=0-1&t=PzZj2EkF1lYhTfSL-1

**Comment by R1tMah** [comment]
here is the link to mine 
https://www.figma.com/design/KvCRYID2rrJUPZ37rMhTnR/STEM-E-Note-Summarizer?node-id=0-1&t=BO39hX6N6EWxMXLn-1

color scheme is for sure susceptible to change.

**Comment by MenlyCSE** [comment]
I added RitVik's file drop concept to the [previous Brainstorm](https://www.figma.com/design/Pj5Et89SAZDB8QdG9KVJ7f/Note-Sage?node-id=0-1&t=wiMDlXsTCKSpN2H5-1)

**Comment by teamtiny123709** [comment]
Here is mine 
https://www.figma.com/design/yTijHrWGdtayCp9d2ootcg/Untitled?node-id=0-1&t=LqB2waa6fQANNST5-1
