### ISSUE TITLE
Brainstorm a Name

### ISSUE THREAD

**Issue by MenlyCSE** [STEM-E-Youth-Career-Development-Program/app-7#6]
Come up with a name for this project: https://docs.google.com/document/d/17If3Xeao7IWeceAFBaAvmSf0Jsoqgj8q1zytesnEsDQ/edit?usp=sharing

**Comment by R1tMah** [comment]
NoteSage 
SmartStudy
STEMStudy
NoteQuizzer
InsightNote

**Comment by MenlyCSE** [comment]
QueryNotes
QuizzyNotes _(reference to 'NoteQuizzer')_
IHateTakingNotes
NoteBuddy

**Comment by teamtiny123709** [comment]
https://www.wordunscrambler.net/word-combiner.aspx

Names
Noteszz
Quizzy
